# Generated by Django 4.0.4 on 2022-04-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('cart_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart',)},
        ),
    ]
