# Generated by Django 4.0.4 on 2022-04-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
    ]
